title: Joe Flynn's Data Analysis Portfolio
author: Joe Flynn
email: joeflynn2012@gmail.com
theme: jekyll-theme-cayman
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of data analysis projects utilizing Python, MySQL, and Tableau

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jflynn2020 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
